### ISSUE TITLE
Incorrect Data Structure for VPG 

### ISSUE THREAD

**Issue by ibadrather** [edreate/Reinforcement_Learning_Course#3]
The current implementation of the Vanilla Policy Gradient (VPG) algorithm uses a data structure that is not optimal. Specifically, the way log probabilities and rewards are extended into batches is inefficient, leading to longer training times and instability in learning.

#### Problem 

The following lines in the implementation seem problematic:

```python
batch_log_probs.extend(episode_log_probs)
batch_rewards.extend(episode_rewards)
```
 
- **Impact** :
  - Inefficient data handling increases computational time.

  - Potential instability in training due to the mismanagement of reward and log-probability data.

#### Suggested Fix 
Reevaluate the design of `batch_log_probs` and `batch_rewards` to use a more efficient and structured approach, such as directly working with tensors instead of lists or flattening the data at a later stage.

#### Additional Notes 

Please confirm if the issue arises due to the structure of these lists or their interaction with subsequent operations in the algorithm.

**Comment by edreate** [comment]
Investigated by you and turns out it is correct
